# Cloudflare Pages configuration

[build]
  command = "./cloudflare-build.sh"
  publish = "dist"
  node_version = "18"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-package-lock"
  # Prevent Yarn from being used
  YARN_ENABLE = "false"