# Cloudflare Pages configuration

[build]
  command = "npm install && npm run build"
  publish = "dist"
  node_version = "18"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-package-lock"